theme: jekyll-theme-minimal
title:  Andre Veiga
description: Assistant Professor of Economics <br/> 
Imperial College London <br/> 
<br/> 
<p><strong>Contact:</strong>  <br/> 
Imperial College Business School <br/> 
South Kensington Campus, London SW12AZ, UK <br/> 
+44 (0)20 7594 7957 <br/> 
<a href="mailto:a.veiga@imperial.ac.uk">a.veiga@imperial.ac.uk</a> <br/></p>
<br/>
<p><a href="https://scholar.google.com/citations?user=C-gmx8QAAAAJ&amp;hl=en">Google Scholar Profile</a></p>
<p><a href="https://www.dropbox.com/s/dbcryohnz4sh8r1/Veiga_CV.pdf?dl=0">CV</a></p>
logo: website_photo.jpeg
