theme: jekyll-theme-minimal
title:  Andre Veiga
description: 
**Assistant Professor of Economics** <br/> 
Interest in theoretical and empirical Industrial Organization, insurance, credit, healthcare.

**Contact:**  <br/>
Imperial College Business School  <br/>
South Kensington Campus, London SW12AZ, UK <br/>
+44 (0)20 7594 7957 <br/>
a.veiga@imperial.ac.uk <br/>

[Google Scholar Profile](https://scholar.google.com/citations?user=C-gmx8QAAAAJ&hl=en)

[CV](https://www.dropbox.com/s/dbcryohnz4sh8r1/Veiga_CV.pdf?dl=0)

logo: website_photo.jpeg
